RegisterNetEvent("evsys:showNotif")
AddEventHandler("evsys:showNotif", function(text) 
    SetNotificationTextEntry('STRING')
	AddTextComponentSubstringPlayerName(text)
	DrawNotification(false, true)
end)